### ISSUE TITLE
Incorporate pagination for returned data

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/website-clinicalgenome-search#38]

**Comment by larrybabb** [comment]
@sgoehringer sorry about switching the milestone and the reverting it. I was viewing how you put this plan together and I thought I was opening a dialogue on the right to see the available milestones, but instead i twitched and selected one. Hopefully no harm done. Really sorry.

**Comment by sgoehringer** [comment]
@larrybabb No worries... the milestones are is currently out of date.  All good.
